const Groq = require("groq-sdk");
const { barajar } = require("../utils/juegosLogica");
const { instruccionVariedad } = require("../utils/variedad");

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });
const MODELO = "openai/gpt-oss-120b";

// Solo letras sueltas: los espacios y guiones no caben en la sopa ni en el ahorcado
const FORMATO_VALIDO = /^[A-Za-z]{3,10}$/;

const RESPALDO = {
  A: [
    { palabra: "house", traduccion: "casa" },
    { palabra: "water", traduccion: "agua" },
    { palabra: "friend", traduccion: "amigo" },
    { palabra: "school", traduccion: "escuela" },
    { palabra: "bread", traduccion: "pan" },
    { palabra: "night", traduccion: "noche" },
    { palabra: "green", traduccion: "verde" },
    { palabra: "table", traduccion: "mesa" },
    { palabra: "street", traduccion: "calle" },
    { palabra: "family", traduccion: "familia" },
    { palabra: "window", traduccion: "ventana" },
    { palabra: "coffee", traduccion: "café" },
    { palabra: "summer", traduccion: "verano" },
    { palabra: "money", traduccion: "dinero" },
    { palabra: "market", traduccion: "mercado" },
    { palabra: "doctor", traduccion: "médico" },
    { palabra: "orange", traduccion: "naranja" },
    { palabra: "kitchen", traduccion: "cocina" },
    { palabra: "morning", traduccion: "mañana" },
    { palabra: "brother", traduccion: "hermano" },
    { palabra: "beach", traduccion: "playa" },
    { palabra: "cloud", traduccion: "nube" },
    { palabra: "horse", traduccion: "caballo" },
    { palabra: "spoon", traduccion: "cuchara" },
    { palabra: "shirt", traduccion: "camisa" },
    { palabra: "clock", traduccion: "reloj" },
    { palabra: "train", traduccion: "tren" },
    { palabra: "river", traduccion: "río" },
    { palabra: "cheese", traduccion: "queso" },
    { palabra: "winter", traduccion: "invierno" },
    { palabra: "letter", traduccion: "carta" },
    { palabra: "flower", traduccion: "flor" },
    { palabra: "island", traduccion: "isla" },
    { palabra: "basket", traduccion: "canasta" },
    { palabra: "pillow", traduccion: "almohada" },
    { palabra: "mirror", traduccion: "espejo" },
    { palabra: "carpet", traduccion: "alfombra" },
    { palabra: "ticket", traduccion: "boleto" },
    { palabra: "pocket", traduccion: "bolsillo" },
    { palabra: "forest", traduccion: "bosque" },
    { palabra: "candle", traduccion: "vela" },
    { palabra: "bridge", traduccion: "puente" },
    { palabra: "yellow", traduccion: "amarillo" },
    { palabra: "hungry", traduccion: "hambriento" },
    { palabra: "garden", traduccion: "jardín" },
    { palabra: "tired", traduccion: "cansado" },
    { palabra: "cheap", traduccion: "barato" },
    { palabra: "heavy", traduccion: "pesado" },
    { palabra: "apple", traduccion: "manzana" },
    { palabra: "baby", traduccion: "bebé" },
    { palabra: "back", traduccion: "espalda" },
    { palabra: "ball", traduccion: "pelota" },
    { palabra: "bear", traduccion: "oso" },
    { palabra: "bed", traduccion: "cama" },
    { palabra: "bell", traduccion: "campana" },
    { palabra: "bird", traduccion: "pájaro" },
    { palabra: "black", traduccion: "negro" },
    { palabra: "blue", traduccion: "azul" },
    { palabra: "boat", traduccion: "bote" },
    { palabra: "body", traduccion: "cuerpo" },
    { palabra: "bone", traduccion: "hueso" },
    { palabra: "book", traduccion: "libro" },
    { palabra: "box", traduccion: "caja" },
    { palabra: "boy", traduccion: "niño" },
    { palabra: "car", traduccion: "coche" },
    { palabra: "cat", traduccion: "gato" },
    { palabra: "chair", traduccion: "silla" },
    { palabra: "child", traduccion: "niño/a" },
    { palabra: "city", traduccion: "ciudad" },
    { palabra: "coat", traduccion: "abrigo" },
    { palabra: "cold", traduccion: "frío" },
    { palabra: "cow", traduccion: "vaca" },
    { palabra: "cup", traduccion: "taza" },
    { palabra: "dance", traduccion: "bailar" },
    { palabra: "dark", traduccion: "oscuro" },
    { palabra: "day", traduccion: "día" },
    { palabra: "dog", traduccion: "perro" },
    { palabra: "door", traduccion: "puerta" },
    { palabra: "dress", traduccion: "vestido" },
    { palabra: "ear", traduccion: "oreja" },
    { palabra: "eat", traduccion: "comer" },
    { palabra: "egg", traduccion: "huevo" },
    { palabra: "eye", traduccion: "ojo" },
    { palabra: "face", traduccion: "cara" },
    { palabra: "fall", traduccion: "otoño/caer" },
    { palabra: "farm", traduccion: "granja" },
    { palabra: "fast", traduccion: "rápido" },
    { palabra: "fire", traduccion: "fuego" },
    { palabra: "fish", traduccion: "pez/pescado" },
    { palabra: "fly", traduccion: "volar/mosca" },
    { palabra: "foot", traduccion: "pie" },
    { palabra: "fun", traduccion: "diversión" },
    { palabra: "girl", traduccion: "niña" },
    { palabra: "glass", traduccion: "vaso/vidrio" },
    { palabra: "good", traduccion: "bueno" },
    { palabra: "hair", traduccion: "cabello" },
    { palabra: "hand", traduccion: "mano" },
    { palabra: "hat", traduccion: "sombrero" },
    { palabra: "head", traduccion: "cabeza" },
    { palabra: "heart", traduccion: "corazón" },
    { palabra: "help", traduccion: "ayuda" },
    { palabra: "home", traduccion: "hogar" },
    { palabra: "hot", traduccion: "caliente" },
    { palabra: "ice", traduccion: "hielo" },
    { palabra: "jump", traduccion: "saltar" },
    { palabra: "key", traduccion: "llave" },
    { palabra: "leg", traduccion: "pierna" },
    { palabra: "light", traduccion: "luz" },
    { palabra: "lion", traduccion: "león" },
    { palabra: "love", traduccion: "amor" },
    { palabra: "man", traduccion: "hombre" },
    { palabra: "milk", traduccion: "leche" },
    { palabra: "moon", traduccion: "luna" },
    { palabra: "mouse", traduccion: "ratón" },
    { palabra: "name", traduccion: "nombre" },
    { palabra: "nose", traduccion: "nariz" },
    { palabra: "paper", traduccion: "papel" },
    { palabra: "park", traduccion: "parque" },
    { palabra: "pen", traduccion: "bolígrafo" },
    { palabra: "pig", traduccion: "cerdo" },
    { palabra: "play", traduccion: "jugar" },
    { palabra: "rain", traduccion: "lluvia" },
    { palabra: "red", traduccion: "rojo" },
    { palabra: "ring", traduccion: "anillo" },
    { palabra: "room", traduccion: "habitación" },
    { palabra: "run", traduccion: "correr" },
    { palabra: "sad", traduccion: "triste" },
    { palabra: "salt", traduccion: "sal" },
    { palabra: "sea", traduccion: "mar" },
    { palabra: "shoe", traduccion: "zapato" },
    { palabra: "shop", traduccion: "tienda" },
    { palabra: "sky", traduccion: "cielo" },
    { palabra: "sleep", traduccion: "dormir" },
    { palabra: "slow", traduccion: "lento" },
    { palabra: "small", traduccion: "pequeño" },
    { palabra: "snow", traduccion: "nieve" },
    { palabra: "song", traduccion: "canción" },
    { palabra: "star", traduccion: "estrella" },
    { palabra: "sun", traduccion: "sol" },
    { palabra: "tall", traduccion: "alto" },
    { palabra: "tea", traduccion: "té" },
    { palabra: "time", traduccion: "tiempo" },
    { palabra: "tree", traduccion: "árbol" },
    { palabra: "white", traduccion: "blanco" },
    { palabra: "wind", traduccion: "viento" },
    { palabra: "woman", traduccion: "mujer" },
    { palabra: "wood", traduccion: "madera" },
    { palabra: "year", traduccion: "año" }
  ],
  B: [
    { palabra: "advice", traduccion: "consejo" },
    { palabra: "borrow", traduccion: "pedir prestado" },
    { palabra: "crowded", traduccion: "abarrotado" },
    { palabra: "deadline", traduccion: "fecha límite" },
    { palabra: "improve", traduccion: "mejorar" },
    { palabra: "journey", traduccion: "viaje" },
    { palabra: "manage", traduccion: "gestionar" },
    { palabra: "neighbour", traduccion: "vecino" },
    { palabra: "opinion", traduccion: "opinión" },
    { palabra: "perhaps", traduccion: "quizás" },
    { palabra: "quality", traduccion: "calidad" },
    { palabra: "reliable", traduccion: "fiable" },
    { palabra: "schedule", traduccion: "horario" },
    { palabra: "though", traduccion: "aunque" },
    { palabra: "unusual", traduccion: "poco común" },
    { palabra: "warning", traduccion: "advertencia" },
    { palabra: "achieve", traduccion: "lograr" },
    { palabra: "budget", traduccion: "presupuesto" },
    { palabra: "confident", traduccion: "seguro de sí mismo" },
    { palabra: "effort", traduccion: "esfuerzo" },
    { palabra: "afford", traduccion: "permitirse" },
    { palabra: "attempt", traduccion: "intento" },
    { palabra: "behave", traduccion: "comportarse" },
    { palabra: "capable", traduccion: "capaz" },
    { palabra: "crowd", traduccion: "multitud" },
    { palabra: "delay", traduccion: "retraso" },
    { palabra: "eager", traduccion: "ansioso" },
    { palabra: "fluent", traduccion: "fluido" },
    { palabra: "gather", traduccion: "reunir" },
    { palabra: "honest", traduccion: "honesto" },
    { palabra: "injury", traduccion: "lesión" },
    { palabra: "mention", traduccion: "mencionar" },
    { palabra: "notice", traduccion: "notar" },
    { palabra: "obvious", traduccion: "obvio" },
    { palabra: "polite", traduccion: "educado" },
    { palabra: "reduce", traduccion: "reducir" },
    { palabra: "shortage", traduccion: "escasez" },
    { palabra: "suggest", traduccion: "sugerir" },
    { palabra: "valuable", traduccion: "valioso" },
    { palabra: "afraid", traduccion: "asustado" },
    { palabra: "benefit", traduccion: "beneficio" },
    { palabra: "careless", traduccion: "descuidado" },
    { palabra: "borrowed", traduccion: "prestado" },
    { palabra: "harmful", traduccion: "dañino" },
    { palabra: "average", traduccion: "promedio" },
    { palabra: "abroad", traduccion: "en el extranjero" },
    { palabra: "accept", traduccion: "aceptar" },
    { palabra: "accident", traduccion: "accidente" },
    { palabra: "account", traduccion: "cuenta" },
    { palabra: "active", traduccion: "activo" },
    { palabra: "admit", traduccion: "admitir" },
    { palabra: "adult", traduccion: "adulto" },
    { palabra: "advantage", traduccion: "ventaja" },
    { palabra: "agree", traduccion: "estar de acuerdo" },
    { palabra: "aim", traduccion: "objetivo" },
    { palabra: "allow", traduccion: "permitir" },
    { palabra: "amount", traduccion: "cantidad" },
    { palabra: "anger", traduccion: "ira" },
    { palabra: "answer", traduccion: "respuesta" },
    { palabra: "anxious", traduccion: "ansioso" },
    { palabra: "apply", traduccion: "aplicar" },
    { palabra: "approach", traduccion: "enfoque / acercarse" },
    { palabra: "argue", traduccion: "discutir" },
    { palabra: "arrive", traduccion: "llegar" },
    { palabra: "article", traduccion: "artículo" },
    { palabra: "attend", traduccion: "asistir" },
    { palabra: "avoid", traduccion: "evitar" },
    { palabra: "awake", traduccion: "despierto" },
    { palabra: "award", traduccion: "premio" },
    { palabra: "balance", traduccion: "equilibrio" },
    { palabra: "base", traduccion: "base" },
    { palabra: "basic", traduccion: "básico" },
    { palabra: "battle", traduccion: "batalla" },
    { palabra: "beauty", traduccion: "belleza" },
    { palabra: "belief", traduccion: "creencia" },
    { palabra: "belong", traduccion: "pertenecer" },
    { palabra: "below", traduccion: "debajo" },
    { palabra: "blame", traduccion: "culpa" },
    { palabra: "blind", traduccion: "ciego" },
    { palabra: "blood", traduccion: "sangre" },
    { palabra: "board", traduccion: "tablero / junta" },
    { palabra: "border", traduccion: "frontera" },
    { palabra: "bother", traduccion: "molestar" },
    { palabra: "brain", traduccion: "cerebro" },
    { palabra: "brave", traduccion: "valiente" },
    { palabra: "breath", traduccion: "aliento" },
    { palabra: "bright", traduccion: "brillante" },
    { palabra: "broad", traduccion: "amplio" },
    { palabra: "build", traduccion: "construir" },
    { palabra: "burn", traduccion: "quemar" },
    { palabra: "bury", traduccion: "enterrar" },
    { palabra: "business", traduccion: "negocio" },
    { palabra: "calm", traduccion: "calma" },
    { palabra: "camp", traduccion: "campamento" },
    { palabra: "care", traduccion: "cuidado" },
    { palabra: "carry", traduccion: "llevar" },
    { palabra: "catch", traduccion: "atrapar" },
    { palabra: "cause", traduccion: "causa" },
    { palabra: "center", traduccion: "centro" },
    { palabra: "century", traduccion: "siglo" },
    { palabra: "chance", traduccion: "oportunidad" },
    { palabra: "change", traduccion: "cambio" },
    { palabra: "charge", traduccion: "cargo" },
    { palabra: "chase", traduccion: "perseguir" },
    { palabra: "choose", traduccion: "elegir" },
    { palabra: "claim", traduccion: "reclamar" },
    { palabra: "clear", traduccion: "claro" },
    { palabra: "climb", traduccion: "escalar" },
    { palabra: "coast", traduccion: "costa" },
    { palabra: "collect", traduccion: "recoger" },
    { palabra: "college", traduccion: "universidad" },
    { palabra: "combine", traduccion: "combinar" },
    { palabra: "comfort", traduccion: "confort" },
    { palabra: "command", traduccion: "mando / orden" },
    { palabra: "common", traduccion: "común" },
    { palabra: "compare", traduccion: "comparar" },
    { palabra: "compete", traduccion: "competir" },
    { palabra: "complain", traduccion: "quejarse" },
    { palabra: "complete", traduccion: "completo" },
    { palabra: "condition", traduccion: "condición" },
    { palabra: "connect", traduccion: "conectar" },
    { palabra: "consider", traduccion: "considerar" },
    { palabra: "contain", traduccion: "contener" },
    { palabra: "continue", traduccion: "continuar" },
    { palabra: "control", traduccion: "control" },
    { palabra: "corner", traduccion: "esquina" },
    { palabra: "correct", traduccion: "correcto" },
    { palabra: "cost", traduccion: "costo" },
    { palabra: "count", traduccion: "contar" },
    { palabra: "course", traduccion: "curso" },
    { palabra: "cover", traduccion: "cubrir" },
    { palabra: "crash", traduccion: "choque" },
    { palabra: "crazy", traduccion: "loco" },
    { palabra: "create", traduccion: "crear" },
    { palabra: "crime", traduccion: "crimen" },
    { palabra: "cross", traduccion: "cruzar" },
    { palabra: "cruel", traduccion: "cruel" },
    { palabra: "cure", traduccion: "cura" },
    { palabra: "curious", traduccion: "curioso" },
    { palabra: "damage", traduccion: "daño" },
    { palabra: "danger", traduccion: "peligro" },
    { palabra: "deal", traduccion: "trato" },
    { palabra: "decide", traduccion: "decidir" },
    { palabra: "degree", traduccion: "grado" },
    { palabra: "demand", traduccion: "demanda" }
  ],
  C: [
    { palabra: "ambiguous", traduccion: "ambiguo" },
    { palabra: "biased", traduccion: "sesgado" },
    { palabra: "cautious", traduccion: "cauteloso" },
    { palabra: "drawback", traduccion: "inconveniente" },
    { palabra: "endeavour", traduccion: "empeño" },
    { palabra: "feasible", traduccion: "viable" },
    { palabra: "grasp", traduccion: "captar" },
    { palabra: "hinder", traduccion: "obstaculizar" },
    { palabra: "insight", traduccion: "perspicacia" },
    { palabra: "leverage", traduccion: "aprovechar" },
    { palabra: "mitigate", traduccion: "mitigar" },
    { palabra: "nuance", traduccion: "matiz" },
    { palabra: "overcome", traduccion: "superar" },
    { palabra: "prompt", traduccion: "impulsar" },
    { palabra: "reluctant", traduccion: "reacio" },
    { palabra: "scrutiny", traduccion: "escrutinio" },
    { palabra: "thorough", traduccion: "minucioso" },
    { palabra: "unveil", traduccion: "desvelar" },
    { palabra: "viable", traduccion: "viable" },
    { palabra: "widespread", traduccion: "generalizado" },
    { palabra: "adverse", traduccion: "adverso" },
    { palabra: "coherent", traduccion: "coherente" },
    { palabra: "entail", traduccion: "conllevar" },
    { palabra: "foster", traduccion: "fomentar" },
    { palabra: "gauge", traduccion: "medir" },
    { palabra: "hamper", traduccion: "entorpecer" },
    { palabra: "inherent", traduccion: "inherente" },
    { palabra: "lucrative", traduccion: "lucrativo" },
    { palabra: "notable", traduccion: "notable" },
    { palabra: "outset", traduccion: "inicio" },
    { palabra: "pervasive", traduccion: "omnipresente" },
    { palabra: "rigorous", traduccion: "riguroso" },
    { palabra: "staunch", traduccion: "firme" },
    { palabra: "tangible", traduccion: "tangible" },
    { palabra: "undermine", traduccion: "socavar" },
    { palabra: "versatile", traduccion: "versátil" },
    { palabra: "yield", traduccion: "ceder" },
    { palabra: "discreet", traduccion: "discreto" },
    { palabra: "eloquent", traduccion: "elocuente" },
    { palabra: "prudent", traduccion: "prudente" },
    { palabra: "sceptical", traduccion: "escéptico" },
    { palabra: "candid", traduccion: "franco" },
    { palabra: "resilient", traduccion: "resiliente" },
    { palabra: "obsolete", traduccion: "obsoleto" },
    { palabra: "arduous", traduccion: "arduo" },
    { palabra: "abolish", traduccion: "abolir" },
    { palabra: "abridge", traduccion: "abreviar" },
    { palabra: "abrogate", traduccion: "abrogar / anular" },
    { palabra: "abscond", traduccion: "fugarse" },
    { palabra: "absolve", traduccion: "absolver" },
    { palabra: "abstain", traduccion: "abstenerse" },
    { palabra: "abstract", traduccion: "abstracto" },
    { palabra: "abstruse", traduccion: "abstruso / incomprensible" },
    { palabra: "absurd", traduccion: "absurdo" },
    { palabra: "abundant", traduccion: "abundante" },
    { palabra: "accelerate", traduccion: "acelerar" },
    { palabra: "accessible", traduccion: "accesible" },
    { palabra: "acclaim", traduccion: "aclamar" },
    { palabra: "accommodate", traduccion: "acomodar" },
    { palabra: "accompany", traduccion: "acompañar" },
    { palabra: "accomplish", traduccion: "lograr" },
    { palabra: "accord", traduccion: "acuerdo" },
    { palabra: "accumulate", traduccion: "acumular" },
    { palabra: "accurate", traduccion: "preciso" },
    { palabra: "accuse", traduccion: "acusar" },
    { palabra: "accustom", traduccion: "acostumbrar" },
    { palabra: "acknowledge", traduccion: "reconocer" },
    { palabra: "acquire", traduccion: "adquirir" },
    { palabra: "acquit", traduccion: "absolver (legal)" },
    { palabra: "acrimonious", traduccion: "cáustico / mordaz" },
    { palabra: "acumen", traduccion: "perspicacia" },
    { palabra: "acute", traduccion: "agudo" },
    { palabra: "adamant", traduccion: "inflexible" },
    { palabra: "adapt", traduccion: "adaptar" },
    { palabra: "adequate", traduccion: "adecuado" },
    { palabra: "adhere", traduccion: "adherirse" },
    { palabra: "adjacent", traduccion: "adyacente" },
    { palabra: "adjourn", traduccion: "aplazar" },
    { palabra: "adjust", traduccion: "ajustar" },
    { palabra: "administer", traduccion: "administrar" },
    { palabra: "admire", traduccion: "admirar" },
    { palabra: "admonish", traduccion: "amonestar" },
    { palabra: "adopt", traduccion: "adoptar" },
    { palabra: "adorn", traduccion: "adornar" },
    { palabra: "adroit", traduccion: "diestro" },
    { palabra: "adulation", traduccion: "adulación" },
    { palabra: "adulterate", traduccion: "adulterar" },
    { palabra: "adversary", traduccion: "adversario" },
    { palabra: "advocate", traduccion: "defender / abogado" },
    { palabra: "aesthetic", traduccion: "estético" },
    { palabra: "affable", traduccion: "afable" },
    { palabra: "affect", traduccion: "afectar" },
    { palabra: "affiliate", traduccion: "afiliar" },
    { palabra: "affinity", traduccion: "afinidad" },
    { palabra: "afflict", traduccion: "afligir" },
    { palabra: "affluent", traduccion: "opulento / rico" },
    { palabra: "aggrandize", traduccion: "engrandecer" },
    { palabra: "aggregate", traduccion: "agregar / total" },
    { palabra: "aghast", traduccion: "horrorizado" },
    { palabra: "agile", traduccion: "ágil" },
    { palabra: "agitate", traduccion: "agitar" },
    { palabra: "alacrity", traduccion: "presteza" },
    { palabra: "alienate", traduccion: "alienar" },
    { palabra: "allege", traduccion: "alegar" },
    { palabra: "alleviate", traduccion: "aliviar" },
    { palabra: "allocate", traduccion: "asignar" },
    { palabra: "allude", traduccion: "aludir" },
    { palabra: "allure", traduccion: "atractivo / seducir" },
    { palabra: "ally", traduccion: "aliado" },
    { palabra: "alter", traduccion: "alterar" },
    { palabra: "altruistic", traduccion: "altruista" },
    { palabra: "amalgamate", traduccion: "amalgamar" },
    { palabra: "ambivalence", traduccion: "ambivalencia" },
    { palabra: "ameliorate", traduccion: "mejorar" },
    { palabra: "amend", traduccion: "enmendar" },
    { palabra: "amiable", traduccion: "amigable" },
    { palabra: "amicable", traduccion: "amistoso" },
    { palabra: "amnesty", traduccion: "amnistía" },
    { palabra: "amorphous", traduccion: "amorfo" },
    { palabra: "ample", traduccion: "amplio" },
    { palabra: "amplify", traduccion: "amplificar" },
    { palabra: "anachronism", traduccion: "anacronismo" },
    { palabra: "analogous", traduccion: "análogo" },
    { palabra: "anarchy", traduccion: "anarquía" },
    { palabra: "anathema", traduccion: "anatema" },
    { palabra: "ancestry", traduccion: "ascendencia" },
    { palabra: "anchor", traduccion: "ancla" },
    { palabra: "ancillary", traduccion: "auxiliar" },
    { palabra: "anguish", traduccion: "angustia" },
    { palabra: "animosity", traduccion: "animosidad" },
    { palabra: "annex", traduccion: "anexar" },
    { palabra: "annihilate", traduccion: "aniquilar" },
    { palabra: "annotate", traduccion: "anotar" },
    { palabra: "annul", traduccion: "anular" },
    { palabra: "anomalous", traduccion: "anómalo" },
    { palabra: "antagonism", traduccion: "antagonismo" },
    { palabra: "antecede", traduccion: "anteceder" },
    { palabra: "antediluvian", traduccion: "antediluviano" },
    { palabra: "anticipate", traduccion: "anticipar" },
    { palabra: "antipathy", traduccion: "antipatía" },
    { palabra: "antiquated", traduccion: "anticuado" },
    { palabra: "apathy", traduccion: "apatía" },
    { palabra: "apex", traduccion: "ápice / cima" },
    { palabra: "appall", traduccion: "espantar" },
    { palabra: "appease", traduccion: "apaciguar" }
  ],
};

/** Traduce el nivel MCER a la banda de dificultad de las listas de respaldo. */
function banda(nivel) {
  const letra = (nivel || "A1").charAt(0).toUpperCase();
  return RESPALDO[letra] ? letra : "A";
}

/** Devuelve palabras de la lista fija, barajadas, para cuando la IA no responde. */
function palabrasDeRespaldo(nivel) {
  return barajar(RESPALDO[banda(nivel)]);
}

/** Pide a la IA palabras del nivel del estudiante con su traducción al español. */
async function generarPalabras({ nivel, cantidad, evitar = [] }) {
  const cuantas = Math.min(Math.max(cantidad || 6, 1), 12);

  const prompt = `Give ${cuantas} English words for a word game, aimed at a Spanish-speaking learner at CEFR level ${nivel}.

Rules for every word:
- a single word, only letters a-z, between 3 and 10 letters long
- no proper nouns, no abbreviations, no hyphens, no spaces
- useful everyday vocabulary at ${nivel} level, not easier and not harder
- all ${cuantas} words must be different from each other

${instruccionVariedad(evitar)}

For each word give a short translation into Spanish.

Reply ONLY with valid JSON:
{"palabras": [{"palabra": "example", "traduccion": "ejemplo"}]}`;

  const completion = await groq.chat.completions.create({
    model: MODELO,
    messages: [{ role: "user", content: prompt }],
    response_format: { type: "json_object" },
    // Temperatura alta a propósito: aquí lo que se busca es que no repita
    temperature: 1.1,
  });

  const datos = JSON.parse(completion.choices[0].message.content);
  const lista = Array.isArray(datos.palabras) ? datos.palabras : [];

  // La IA a veces devuelve frases o palabras larguísimas: aquí se descartan
  return lista.filter(
    (p) => p && FORMATO_VALIDO.test(p.palabra || "") && (p.traduccion || "").trim(),
  );
}

module.exports = { FORMATO_VALIDO, palabrasDeRespaldo, generarPalabras };
